services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - webpnk-network

    webserver:
        image: nginx:alpine
        ports:
            - "8181:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - webpnk-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: webpnk-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
        ports:
            - "33068:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - webpnk-network
        command: --default-authentication-plugin=mysql_native_password

#    ssr:
#        build:
#            context: .
#        volumes:
#            - ./:/var/www
#        command: [ "php", "/var/www/artisan", "inertia:start-ssr" ]
#        stop_signal: SIGTERM
#        healthcheck:
#            test: [ "CMD", "php", "/var/www/artisan", "ssr:healthcheck" ]
#            start_period: 3600s
#        networks:
#            - letmename-network

    queue:
        build:
            context: .
        volumes:
            - ./:/var/www
        command: [ "php", "/var/www/artisan", "queue:work", "--tries=3", "--verbose" ]
        depends_on:
            - db
        networks:
            - webpnk-network
volumes:
    dbdata:

networks:
    webpnk-network:
